version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000" # Porta externa:interna
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/blogging
    volumes:
      - .:/app
    command: npm start

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
