name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      APPLICATION_PORT: ${{ vars.APPLICATION_PORT }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test:cov

      - name: Build and Push Docker Image
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t $DOCKER_USERNAME/blogging-service:latest --build-arg DATABASE_URL=$DATABASE_URL --build-arg APPLICATION_PORT=$APPLICATION_PORT .
          docker push $DOCKER_USERNAME/blogging-service:latest
